include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/_deployment.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/maintenance.yml'

stages:
  - deploy
  - maintenance

variables:
  PROJECT_PARENT_NAME: elastic

# Deployment

.deploy:
  variables:
    STACK: ${PROJECT_PARENT_NAME}
    STATUS_CHECK_DELAY: 30

# Curator deployment

.deploy-curator:
  variables: &deploy-curator-variables
    SERVICES_TO_CHECK: ${PROJECT_PARENT_NAME}_${CI_PROJECT_NAME}

.deploy-curator-development:
  extends: .deploy-development
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}.tmpl.yml:docker-compose.${CI_PROJECT_NAME}.dev.yml
    <<: *deploy-curator-variables
  environment:
    name: dev/${CI_PROJECT_NAME}

.deploy-curator-production:
  extends: .deploy-production
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}.tmpl.yml:docker-compose.${CI_PROJECT_NAME}.prod.yml
    <<: *deploy-curator-variables
  environment:
    name: pro/${CI_PROJECT_NAME}

.deploy-curator-support-branch: &deploy-curator-support-branch
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule" ||
          $CI_PIPELINE_SOURCE == "web" ||
          $CI_COMMIT_BRANCH == "master"
      when: never
    - if: $CI_COMMIT_BRANCH
      when: manual
      allow_failure: true

deploy-curator-support-branch-development:
  extends: .deploy-curator-development
  <<: *deploy-curator-support-branch

.deploy-curator-stable-branch: &deploy-curator-stable-branch
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule" ||
          $CI_PIPELINE_SOURCE == "web"
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
      allow_failure: true

deploy-curator-stable-branch-development:
  extends: .deploy-curator-development
  <<: *deploy-curator-stable-branch

deploy-curator-stable-branch-production:
  extends: .deploy-curator-production
  <<: *deploy-curator-stable-branch

.deploy-curator-tag: &deploy-curator-tag
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: true

deploy-curator-tag-development:
  extends: .deploy-curator-development
  <<: *deploy-curator-tag

deploy-curator-tag-production:
  extends: .deploy-curator-production
  <<: *deploy-curator-tag

# Curator-restore deployment

.deploy-curator-restore:
  variables: &deploy-curator-restore-variables
    SERVICES_TO_CHECK: ${PROJECT_PARENT_NAME}_${CI_PROJECT_NAME}-restore

.deploy-curator-restore-development:
  extends: .deploy-development
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-restore.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-restore.dev.yml
    <<: *deploy-curator-restore-variables
  environment:
    name: dev/${CI_PROJECT_NAME}-restore

.deploy-curator-restore-production:
  extends: .deploy-production
  variables:
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}-restore.tmpl.yml:docker-compose.${CI_PROJECT_NAME}-restore.prod.yml
    <<: *deploy-curator-restore-variables
  environment:
    name: pro/${CI_PROJECT_NAME}-restore

.deploy-curator-restore-support-branch: &deploy-curator-restore-support-branch
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule" ||
          $CI_COMMIT_BRANCH == "master"
      when: never
    - if: $CI_COMMIT_BRANCH &&
          $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true

deploy-curator-restore-support-branch-development:
  extends: .deploy-curator-restore-development
  <<: *deploy-curator-restore-support-branch

.deploy-curator-restore-stable-branch: &deploy-curator-restore-stable-branch
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "master" &&
          $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true

deploy-curator-restore-stable-branch-development:
  extends: .deploy-curator-restore-development
  <<: *deploy-curator-restore-stable-branch

deploy-curator-restore-stable-branch-production:
  extends: .deploy-curator-restore-production
  <<: *deploy-curator-restore-stable-branch

# Old-curator deployment
# Jobs temporales, hasta unificar Elasticsearch v5 y v6

.deploy-old-curator:
  variables: &deploy-old-curator-variables
    SERVICES_TO_CHECK: ${PROJECT_PARENT_NAME}_old-${CI_PROJECT_NAME}

.deploy-old-curator-development:
  extends: .deploy-development
  variables:
    COMPOSE_FILE: docker-compose.old-${CI_PROJECT_NAME}.tmpl.yml:docker-compose.old-${CI_PROJECT_NAME}.dev.yml
    <<: *deploy-old-curator-variables
  environment:
    name: dev/old-${CI_PROJECT_NAME}

.deploy-old-curator-production:
  extends: .deploy-production
  variables:
    COMPOSE_FILE: docker-compose.old-${CI_PROJECT_NAME}.tmpl.yml:docker-compose.old-${CI_PROJECT_NAME}.prod.yml
    <<: *deploy-old-curator-variables
  environment:
    name: pro/old-${CI_PROJECT_NAME}

.deploy-old-curator-support-branch: &deploy-old-curator-support-branch
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule" ||
          $CI_COMMIT_BRANCH == "master"
      when: never
    - if: $CI_COMMIT_BRANCH &&
          $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true

deploy-old-curator-support-branch-development:
  extends: .deploy-old-curator-development
  <<: *deploy-old-curator-support-branch

.deploy-old-curator-stable-branch: &deploy-old-curator-stable-branch
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "master" &&
          $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true

deploy-old-curator-stable-branch-development:
  extends: .deploy-old-curator-development
  <<: *deploy-old-curator-stable-branch

deploy-old-curator-stable-branch-production:
  extends: .deploy-old-curator-production
  <<: *deploy-old-curator-stable-branch

# Maintenance

.scheduled-run:
  variables:
    STACK: ${PROJECT_PARENT_NAME}
    SERVICE: ${PROJECT_PARENT_NAME}_${CI_PROJECT_NAME}

# Job temporal, hasta unificar Elasticsearch v5 y v6
scheduled-run-old-curator-production:
  extends: scheduled-run-production
  variables:
    SERVICE: ${PROJECT_PARENT_NAME}_old-${CI_PROJECT_NAME}
