---
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 30 (by default) days (based on index name), for 'fluentd-' prefixed indices. Ignore
      the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      continue_if_exception: False
      disable_action: ${DELETE_OLD_LOGS_DISABLE:False}
    filters:
    - filtertype: pattern
      kind: prefix
      value: ${LOG_INDEX_PREFIX:fluentd-}
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y%m%d'
      unit: days
      unit_count: ${DELETE_OLD_LOGS_DAYS_COUNT:30}

  2:
    action: snapshot
    description: >-
      Snapshot selected indices to repository ('s3-backup' by default) with automatic snapshot name.
      Exclude log indices.
    options:
      repository: ${SNAPSHOT_REPOSITORY:s3-backup}
      name: # default is 'curator-%Y%m%d%H%M%S'
      wait_for_completion: True
      max_wait: 3600
      wait_interval: 30
      disable_action: ${SNAPSHOT_DISABLE:False}
    filters:
    - filtertype: pattern
      kind: prefix
      value: ${LOG_INDEX_PREFIX:fluentd-}
      exclude: True
    - filtertype: pattern
      kind: prefix
      value: searchguard
      exclude: True

  3:
    action: delete_snapshots
    description: >-
      Delete old snapshots (90 by default) from repository ('s3-backup' by default).
    options:
      repository: ${SNAPSHOT_REPOSITORY:s3-backup}
      ignore_empty_list: True
      retry_interval: 120
      retry_count: 3
      disable_action: ${DELETE_OLD_SNAPSHOTS_DISABLE:False}
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y%m%d'
      unit: days
      unit_count: ${DELETE_OLD_SNAPSHOTS_DAYS_COUNT:90}

  4:
    action: restore
    description: >-
      Restore snapshot by name from repository ('s3-backup' by default). Disabled by default.
    options:
      repository: ${SNAPSHOT_REPOSITORY:s3-backup}
      name: ${SNAPSHOT_RESTORE_NAME}
      indices:
      - ${SNAPSHOT_RESTORE_INDICES}
      include_aliases: ${SNAPSHOT_RESTORE_INCLUDE_ALIASES:True}
      wait_interval: 30
      disable_action: ${RESTORE_SNAPSHOT_DISABLE:True}
    filters:
    - filtertype: state
      state: SUCCESS
