---
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than ${DELETE_OLD_LOGS_DAYS_COUNT} (30 by default) days (based on index name), for 'fluentd-'
      prefixed indices. Ignore the error if the filter does not result in an actionable list of indices
      (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: ${DELETE_OLD_LOGS_DISABLE:False}
    filters:
    - filtertype: pattern
      kind: prefix
      value: fluentd-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y%m%d'
      unit: days
      unit_count: ${DELETE_OLD_LOGS_DAYS_COUNT:30}
      exclude:
