---
client:
  hosts:
    - ${ELASTICSEARCH_URL}
  port: ${ELASTICSEARCH_PORT}
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth: ${ELASTICSEARCH_AUTH}
  timeout: ${CURATOR_TIMEOUT}
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
