version: '3.5'

services:
  curator:
    image: ${IMAGE_NAME:-bobrik/curator}:${IMAGE_TAG:-latest}
    command: ${CURATOR_ACTIONS_PATH}
    environment:
      ELASTICSEARCH_URL:
      ELASTICSEARCH_AUTH: ${ES_USER}:${ES_PASS}
      ELASTICSEARCH_PORT:
      CURATOR_TIMEOUT:
      LOG_INDEX_PREFIX:
      DELETE_OLD_LOGS_TIMESTRING:
      DELETE_OLD_LOGS_MONTHS_COUNT:
      SNAPSHOT_REPOSITORY:
      DELETE_OLD_SNAPSHOTS_DAYS_COUNT:
      DELETE_OLD_LOGS_DISABLE:
      SNAPSHOT_DISABLE:
      DELETE_OLD_SNAPSHOTS_DISABLE:
      RESTORE_SNAPSHOT_DISABLE:
    networks:
      elastic-net:
    configs:
      - source: curator-config
        target: ${CURATOR_CONFIG_PATH}
      - source: curator-actions
        target: ${CURATOR_ACTIONS_PATH}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        condition: on-failure
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-32M}

networks:
  elastic-net:
    name: ${ELASTIC_NET_NAME}
    driver: ${ELASTIC_NET_DRIVER}
    external: true

configs:
  curator-config:
    name: ${CURATOR_CONFIG_CONFIG_NAME}
    file: ./config/curator.yml

  curator-actions:
    name: ${CURATOR_ACTIONS_CONFIG_NAME}
    file: ./config/actions.yml
