version: '3.5'

services:
  curator-restore:
    image: bobrik/curator:${IMAGE_TAG:-latest}
    command: /.curator/actions.yml
    environment:
      - ELASTICSEARCH_URL
      - ELASTICSEARCH_AUTH
      - ELASTICSEARCH_PORT
      - CURATOR_TIMEOUT
      - SNAPSHOT_REPOSITORY
      - SNAPSHOT_RESTORE_NAME
      - SNAPSHOT_RESTORE_INDICES
      - DELETE_OLD_LOGS_DISABLE=True
      - SNAPSHOT_DISABLE=True
      - DELETE_OLD_SNAPSHOTS_DISABLE=True
      - RESTORE_SNAPSHOT_DISABLE=False
    networks:
      - elastic-net
    configs:
      - source: curator-config
        target: /.curator/curator.yml
      - source: curator-actions
        target: /.curator/actions.yml
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          memory: 103M

networks:
  elastic-net:
    name: ${ELASTIC_NET_NAME:-elastic6-net}
    external: true

configs:
  curator-config:
    name: ${CURATOR_CONFIG_NAME:-curator-config}
    file: ./config/curator.yml

  curator-actions:
    name: ${CURATOR_ACTIONS_NAME:-curator-actions}
    file: ./config/actions.yml
